services:
  sistema-escola:
    build: .
    container_name: sistema_escola
    volumes:
      - .:/app
      - /app/frontend/node_modules # Isso impede que seu PC apague os módulos do container
    ports:
      - "8080:8080"