services:
  sistema-escola:
    build: .
    container_name: sistema_escola
    volumes:
      - .:/app
      - /app/frontend/node_modules
      - ./database:/app/database # Força a persistência específica da pasta do banco
    ports:
      - "8080:8080"