services:
  sistema-escola:
    build: .
    container_name: sistema_residencia
    volumes:
      - ./database:/app/database
      - .:/app  # Sincroniza a pasta atual com a pasta /app do container
    ports:
      - "8080:8080"  # Porta externa : Porta interna do Gotty
    stdin_open: true
    tty: true